### GET
GET http://localhost:4000/categoria

### GET rer.query
GET http://localhost:4000/categoria?id_categoria=1
### GET rer.query
GET http://localhost:4000/categoria?descripcion_categoria=catedProd3
### GET rer.query
GET http://localhost:4000/categoria?tipo=insumo
### GET rer.query
GET http://localhost:4000/categoria?visibilidad=false


### GET ID
GET http://localhost:4000/categoria/8

### POST
POST http://localhost:4000/categoria
Content-Type: application/json

{
  "descripcion_categoria" : "catedNueva",
  "tipo" : "insumo"
}


### PATCH
PATCH http://localhost:4000/categoria/10
Content-Type: application/json

{
  "tipo": "producto"
}

### DELETE
DELETE http://localhost:4000/categoria/10


