### GET
GET http://localhost:4000/insumo

### GET rer.query
GET http://localhost:4000/insumo?nombre=Leche
### GET rer.query
GET http://localhost:4000/insumo?categoria=categoria3


### GET ID
GET http://localhost:4000/insumo/8

### POST
POST http://localhost:4000/insumo
Content-Type: application/json

{
  "img_url": "imagen100.jpg",
  "nombre": "Ambrosia",
  "cantidad": "15.0",
  "categoria": "categoria3",
  "medida": "kilogramo"
}


### PATCH
PATCH http://localhost:4000/insumo/16
Content-Type: application/json

{
  "cantidad": "18.0"
}

### DELETE
DELETE http://localhost:4000/insumo/16


