### GET
GET http://localhost:4000/insumo

### GET rer.query
GET http://localhost:4000/insumo?nombre=Ambrosia
### GET rer.query
GET http://localhost:4000/insumo?categoria=catedInsu3
### GET rer.query
GET http://localhost:4000/insumo?visibilidad=false


### GET ID
GET http://localhost:4000/insumo/21

### POST
POST http://localhost:4000/insumo
Content-Type: application/json

{
  "img_url": "/insumo/ejemplo-insumo.png",
  "nombre": "Ambrosia",
  "cantidad": 15.0,
  "id_categoria": "6",
  "medida": "kilogramo"
}


### PATCH
PATCH http://localhost:4000/insumo/22
Content-Type: application/json

{
  "cantidad": "18.0"
}

### DELETE
DELETE http://localhost:4000/insumo/22


