### GET
GET http://localhost:4000/lista-producto

### GET ID
GET http://localhost:4000/lista-producto/1000/1

### GET ID
GET http://localhost:4000/lista-producto/1004

### POST
POST http://localhost:4000/lista-producto
Content-Type: application/json

{
  "id_producto": 3,
  "cantidad": 4,
  "id_pedido": 1004,
  "precio_cantidad": 20.10,
  "nombre": "CONO PIZZA"
}


### PATCH
PATCH http://localhost:4000/lista-producto/1004
Content-Type: application/json

{
  "id_producto": "3",
  "precio_cantidad": "21"
}

### DELETE
DELETE http://localhost:4000/lista-producto/1004/3


