### GET
GET http://localhost:4000/lista-promocion

### GET ID
GET http://localhost:4000/lista-promocion/1009/5

### GET ID
GET http://localhost:4000/lista-promocion/1009

### POST
POST http://localhost:4000/lista-promocion
Content-Type: application/json

{
  "id_promocion": 2,
  "cantidad": 4,
  "id_pedido": 1009,
  "precio_cantidad": 45.85,
  "nombre": "PROMO OTOÑO"
}


### PATCH
PATCH http://localhost:4000/lista-promocion/1009
Content-Type: application/json

{
  "id_promocion": "2",
  "precio_cantidad": "60"
}

### DELETE
DELETE http://localhost:4000/lista-promocion/1009/2


git config --global user.name "Elian Paniagua"
git config --global user.email "eypaniaguam@unjbg.edu.pe"