### GET
GET http://localhost:4000/producto-insumo

### GET rer.query
GET http://localhost:4000/producto-insumo?id_producto=1
### GET rer.query
GET http://localhost:4000/producto-insumo?id_insumo=2

### GET ID
GET http://localhost:4000/producto-insumo/2

### POST
POST http://localhost:4000/producto-insumo
Content-Type: application/json

{
  "id_producto": 5,
  "id_insumo": 4,
  "cantidad": 12
}


### PATCH
PATCH http://localhost:4000/producto-insumo/5
Content-Type: application/json

{
  "id_insumo": 4,
  "cantidad": 120
}

### DELETE
DELETE http://localhost:4000/producto-insumo/5/4


