### GET
GET http://localhost:4000/producto

### GET rer.query
GET http://localhost:4000/producto?precio=10.00
### GET rer.query
GET http://localhost:4000/producto?categoria=categoria3
### GET rer.query
GET http://localhost:4000/producto?visibilidad=false


### GET ID
GET http://localhost:4000/producto/8

### POST
POST http://localhost:4000/producto
Content-Type: application/json

{
  "img_url": "sandwish_arcoiris.jpg",
  "nombre": "sandwish sabor arcoiris", 
  "descripcion": "sandwish de colores con muchos sabores",
  "precio_base": "15.0",
  "categoria": "categoria3"
}


### PATCH
PATCH http://localhost:4000/producto/8
Content-Type: application/json

{
  "visibilidad": "true"
}

### DELETE
DELETE http://localhost:4000/producto/8


