### GET
GET http://localhost:4000/promocion

### GET rer.query
GET http://localhost:4000/promocion?categoria=catedProm1
### GET rer.query
GET http://localhost:4000/promocion?dia_promocion=miércoles
### GET rer.query
GET http://localhost:4000/promocion?nombre=promocion%20por%20default

### GET rer.query
GET http://localhost:4000/promocion?visibilidad=false


### GET ID
GET http://localhost:4000/promocion/7

### POST
POST http://localhost:4000/promocion
Content-Type: application/json

{
  "img_url": "/promocion/ejemplo-promocion7.png",
  "nombre": "Jueves de patas",
  "descripcion": "Ven con tus amigos.",
  "precio_base": "70.00",
  "id_categoria": 7,
  "precio_oferta": "50.00",
  "estado_promocion": true,
  "dia_promocion": "jueves",
  "fecha_inicio": "2024-05-30",
  "fecha_fin": "2024-06-30"
}


### PATCH
PATCH http://localhost:4000/promocion/35
Content-Type: application/json

{
  "img_url": "https://images.unsplash.com/photo-1570786097801-b8b9531ed5cb?q=80&w=1674&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}


### DELETE
DELETE http://localhost:4000/promocion/35


