### GET
GET http://localhost:4000/usuario
### GET rer.query
GET http://localhost:4000/usuario?telefono=956565656
###
GET http://localhost:4000/usuario?validacion=true
### GET ID
GET http://localhost:4000/usuario/28

### POST
POST http://localhost:4000/usuario
Content-Type: application/json

{
  "img_url": "usuarioexpres.jpg",
  "nombre": "Ronald",
  "apellido": "Steven Obama",
  "documento": "13579132",
  "tipo_doc": "DNI",
  "telefono": "956565656"
}


### PATCH
PATCH http://localhost:4000/usuario/28
Content-Type: application/json

{
  "validacion": "true"
}

### DELETE
DELETE http://localhost:4000/usuario/28


